### ISSUE TITLE
Visualization of occupancy volume

### ISSUE THREAD

**Issue by moeinheidari7829** [LabShuHangGU/FR-INR#1]
Dear authors,

Thank you for the excellent code! I am trying to replicate the results of the occupancy volume experiment described in your paper. The network outputs are in .dae format, which allows visualization in tools like MeshLab. However, I cannot visualize the ground truth as shown in the paper, and the .ply file from the 3D Stanford website appears different.

Could you please assist me in converting the ground-truth data (provided in .mat format by you) into a .dae file to match the visualization presented in your paper?

**Comment by galijipaifan** [comment]
goog

**Comment by KexuanShi** [comment]
Thanks for your attention!

I have updated the code for saving DAE files. The images in the paper are directly generated and exported from DAE files using MeshLab.

**Comment by moeinheidari7829** [comment]
> Thanks for your attention!
> 
> I have updated the code for saving DAE files. The images in the paper are directly generated and exported from DAE files using MeshLab.

Thank you very much for your prompt response. Really appreciate it. Can you please guide me on how you generated the ground-truth mesh in .dae format from its .mat source to visualize it in the paper? Specifically I am not able to generate the same image as your paper for the ground-truth. Thanks again

**Comment by KexuanShi** [comment]
I think you can comment out the training code, run the 3D_occupance.py file, and directly save the real .mat file you read as a .dae.

**Comment by moeinheidari7829** [comment]
> I think you can comment out the training code, run the 3D_occupance.py file, and directly save the real .mat file you read as a .dae.

Thank you very much for your help. I solved it and I am going to close the issues. Congrats on the great work again!
