### ISSUE TITLE
comments in modules.py

### ISSUE THREAD

**Issue by kyleok** [LabShuHangGU/FR-INR#2]
hi, thanks for sharing great work.
I found this in the modules.py,
I used translator, is this something unresolved yet?
https://github.com/LabShuHangGU/FR-INR/blob/398b64d8384106157535a36f3eedf7005f8c3996/modules.py#L249

**Comment by KexuanShi** [comment]
Hi, kyleok!

Thanks for your feedback! I think that this should just be a code comment at that time to remind me some modifications. There should not be any unresolved problem. If you have any problem for reproduction, please let me know!

**Comment by kyleok** [comment]
Thanks for confirming.
Btw, really nice repo. Its hard to see works like this to actually run without dependencies problem.
